eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: zuul-server
zuul:
  routes:
    info-service:
      path: /info/**
      serviceId: sinochem-cloud-info-service
    order-service:
      path: /order/**
      serviceId: sinochem-cloud-order-service